# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 00:11
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161016_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/Lethero/Furryous/media'), upload_to=b'', verbose_name=b'Profile Picture'),
        ),
    ]
